name: Run Python Script3

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16 * * *'  # هر روز ساعت 00:00 UTC اجرا می‌شود

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # نسخه پایتون مورد نظر خود را انتخاب کنید

    - name: Install dependencies
      run: |
        pip install pyrogram  # اگر نیاز به نصب بسته‌ها دارید

    - name: Run Python Script
      run: |
        python your_script.py  # جایگزین کنید با نام فایل پایتون خود
